services:
  skald-anonymisation:
    image: ghcr.io/kailash-reddy/skald:latest
    volumes:
      - /tmp/SKALD_input/input_file:/app/data
      - /tmp/SKALD_input/config:/app/config
      - /tmp/SKALD_output:/app/output
