services:
  arx-anonymisation:
    image: ghcr.io/prathmeshj1729/arx_pipeline:latest
    volumes:
      - /tmp/arx_input/input_file:/app/data
      - /tmp/arx_input/config:/app/config
      - /tmp/arx_output:/app/output/anonymized_chunks
    ports:
      - "8070:8070"