services:
  differential-privacy:
    image: ghcr.io/kailash-reddy/differential-privacy:v1
    volumes:
      - /tmp/SKALD_input/input_file:/app/data
      - /tmp/SKALD_input/config:/app/config
      - /tmp/SKALD_output:/app/output
