services:
  skald-anonymisation:
    image: ghcr.io/kailash-reddy/skald:latest
    volumes:
      - /tmp/skald_input/input_file:/app/data
      - /tmp/skald_input/config:/app/config
      - /tmp/skald_output:/app/output
    ports:
      - "8070:8070"